FROM alpine@sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930
#LABEL maintainer="3241034+Emdot@users.noreply.github.com"
MAINTAINER 3241034+Emdot@users.noreply.github.com
LABEL sample-label-a="alpha"
LABEL sample-label-g="gamma"
LABEL org.opencontainers.image.title="A second sample image for testing image inspection"

WORKDIR sample
