# syntax=docker/dockerfile:1.2
FROM ddnt:parent
#LABEL maintainer="3241034+Emdot@users.noreply.github.com"
MAINTAINER 3241034+Emdot@users.noreply.github.com
LABEL sample-label-a="alpha"
LABEL sample-label-g="gamma"
LABEL org.opencontainers.image.title="A second sample image for testing image inspection"

WORKDIR sample
