# syntax=docker/dockerfile:1.2
FROM ddnt:parent
MAINTAINER 3241034+Emdot@users.noreply.github.com
LABEL sample-label-a="alpha"
LABEL sample-label-b="beta"
LABEL label-with-equals="abc=def"
LABEL override-1="from-image"
LABEL override-2="from-image"
LABEL org.opencontainers.image.title="Sample image for testing image inspection"

WORKDIR sample
